spring.application.name=webhook-platform

spring.datasource.url=jdbc:postgresql://localhost:5433/webhook_platform
spring.datasource.username=webhook_user
spring.datasource.password=webhook_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info